# _config.yml for Minimal Mistakes theme
title: "Your Name's Portfolio"
description: "A Data Analyst's Portfolio showcasing projects, certifications, and research."
url: "https://aleezazia.github.io"   # Update this with your GitHub Pages URL or custom domain

remote_theme: "mmistakes/minimal-mistakes@4.27.2"  # Tells GitHub to use Minimal Mistakes theme

# Add other personal details like your name, bio, etc.
author:
  name: "Aleeza Zia"
  bio: "Data Analyst | Passionate About Data Science"
  email: "aleezazia27@example.com"
  links:
    - icon: "github"
      url: "https://github.com/AleezaZia27"
    - icon: "linkedin"
      url: "https://www.linkedin.com/in/aleezazia27/"
